# Generated by Django 4.1.4 on 2022-12-12 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('ID', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор контакта')),
                ('NAME', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Адрес электронной почты')),
                ('VALUE_TYPE', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип электронной почты')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EMAIL', to='api_v1.contacts', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('ID', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор сделки')),
                ('contacts', models.ManyToManyField(db_index=True, to='api_v1.contacts')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('ID', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор компании')),
                ('TITLE', models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='Название')),
                ('contacts', models.ManyToManyField(db_index=True, to='api_v1.contacts')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компания',
            },
        ),
    ]
