version: '1.1'

services:
  web:
    build: ./mdcproject
    command: gunicorn mdcproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./mdcproject/:/usr/src/mdcproject/
    ports:
      - 8000:8000
    env_file:
      - ./.env
